// ---------------------------------------------------------------------------
// WASM + JSFFI loader for Reflex applications
//
// This script:
//   1. Sets up WASI (browser_wasi_shim) for the Haskell RTS
//   2. Loads the JSFFI glue code generated by GHC's post-linker
//   3. Instantiates the WASM module with both WASI and JSFFI imports
//   4. Calls hs_start() — the exported Haskell entry point
// ---------------------------------------------------------------------------

import { WASI, OpenFile, File, ConsoleStdout }
  from "https://cdn.jsdelivr.net/npm/@bjorn3/browser_wasi_shim@0.3.0/dist/index.js";
import ghc_wasm_jsffi from "./ghc_wasm_jsffi.js";

// Set up WASI with basic stdio
const wasi = new WASI(
  [],                        // command-line args
  ["GHCRTS=-H64m"],          // environment variables (set RTS heap size)
  [
    new OpenFile(new File([])),                   // fd 0: stdin
    ConsoleStdout.lineBuffered(msg => console.log(`[WASI stdout] ${msg}`)),
    ConsoleStdout.lineBuffered(msg => console.warn(`[WASI stderr] ${msg}`)),
  ],
  { debug: false }
);

// Instantiate the WASM module with knot-tying for JSFFI exports
const instance_exports = {};
const { instance } = await WebAssembly.instantiateStreaming(
  fetch("bin.wasm"),
  {
    wasi_snapshot_preview1: wasi.wasiImport,
    ghc_wasm_jsffi: ghc_wasm_jsffi(instance_exports),
  }
);
Object.assign(instance_exports, instance.exports);

// Initialize WASI (calls _initialize in the reactor module)
wasi.initialize(instance);

// Launch the Reflex application
await instance.exports.hs_start();
